### ISSUE TITLE
Request to add License File

### ISSUE THREAD

**Issue by abhinavsharma1498** [techascent/tech.config#5]
Hi Maintainers,
This project is missing a license file, which is blocking its usage, as well as dependent projects (like dtype-next, tablecloth, etc).
Can you please add an appropriate license file?

Thank you

**Comment by harold** [comment]
![image](https://github.com/techascent/tech.config/assets/7443/4ae36935-e538-4059-b0cc-cb7dffbe2c60)

Welcome in, does the referenced change solve your issue?

Fun to get interactions from so far, hope you're well - what are you using this library for?

**Comment by abhinavsharma1498** [comment]
Thank you @harold. This change solves my issue. I am using tavlecloth for some data interpretation which brought this in as a transitive dependency.

**Comment by harold** [comment]
Very cool! Welcome in. Glad to help.
